### ISSUE TITLE
Compatibility with `discord-topic-author`

### ISSUE THREAD

**Issue by Stanzilla** [merefield/discourse-topic-list-previews-theme#10]
Hey there, I really like the new component version over the plugin, but it sadly breaks when I use https://meta.discourse.org/t/discourse-topic-author/111021

**Comment by merefield** [comment]
Yeah, that might not be compatible.  I'm afraid you are going to have to drill into the CSS used in that Theme and adapt it for use with this Component, because I'm significantly overriding the layout so there may be some differences to the base layout.
