### ISSUE TITLE
Why does this one topic always have topic-list as tiles?

### ISSUE THREAD

**Issue by craigconstantine** [merefield/discourse-topic-list-previews-theme#4]
This is going to be hard for you to reproduce. I'm hoping this is enough to give a hint to find the bug in the code. If you need to see this in action, I can put you into a group, in my discourse platform so you can see the category.

On https://forum.podcaster.community (which is hosted by Discourse.com) I have two categories intentionally configured so the Topic List Previews component displays as tiles

![8cf61f45916097adfbbe9615864b675fc182cb90_2_690x152](https://user-images.githubusercontent.com/2278992/129413739-76f1a665-9e98-46bb-b846-0aa0fe6383ff.png)

https://forum.podcaster.community/c/supporters-podcasts/10  
https://forum.podcaster.community/c/snapshots/17  

The question is, why does this other category also display as tiles:
(Note that this category is restricted to a particular group, keeping normal users out.)

<img width="375" alt="Screen Shot 2021-08-13 at 16 14 41" src="https://user-images.githubusercontent.com/2278992/129413855-21f1ec41-7b1d-446a-8015-41cb976edacd.png">

The mystery deepens; If I remove those two categories from the “topic list tiles categories” setting, shown above—by using the [reset] button… BOOP, my supporters-only category suddenly shows up as a list. When I re-add them into the config, the supporters-only immediately flips to as-tiles display.

( Yes, I’m clearing cache and forcing reload each step of the way. :)

**Comment by craigconstantine** [comment]
le BUMP ?

**Comment by merefield** [comment]
Thanks for patience, I suspect this is an edge case.  Unfortunately, this may need a significant refactor to work correctly.  I'll look at that soon.

**Comment by merefield** [comment]
FYI I've started working on this and made some significant progress.

**Comment by merefield** [comment]
OK, at a point when you could test the branch, if you have time:

https://github.com/merefield/discourse-topic-list-previews-theme/pull/5

branch is `add_ember_service_remove_jquery`

If you want to test it (would be appreciated), you can load this as an additional Component (fill in the branch box under Advanced), edit it's name and add it to a Theme you can switch too that your users don't normally use.

**Comment by craigconstantine** [comment]
<img width="798" alt="Screen Shot 2021-09-09 at 11 39 33" src="https://user-images.githubusercontent.com/2278992/132717663-67c5e59d-9da7-4023-8461-6a4ef3bca328.png">

<img width="695" alt="Screen Shot 2021-09-09 at 11 39 44" src="https://user-images.githubusercontent.com/2278992/132717694-6fc2e850-3526-4fcf-92b2-65bd79e956a5.png">

**Comment by craigconstantine** [comment]
That fixes my callout, yes.

If you want to kick it around on the live site, go make a login https://forum.podcaster.community/ and I can add you to the supporters-only group so you can see everything that normal users see.

**Comment by merefield** [comment]
@craigconstantine thanks for that offer, but I have it on a local and deployed site already.

What I may do is leave it on this branch for a week and see how things fare.  Let me know of anything bad!  I'll post on meta.

Thanks for confirming your issue is resolved, that is what I'd hoped, but came about it in a very indirect way :)

**Comment by craigconstantine** [comment]
Sanity check of my thinking: I have one Discourse install that has the main branch; that shows as 'currently up to date'. I have another Discourse install [the one we were discussing above] that I still have on the add_ember_service_remove_jquery branch which is showing 11 commits behind.

Shall I update my add_ember_service_remove_jquery branch component to keep up… or is it too bleeding edge?

**Comment by merefield** [comment]
Yes please, if you can update that branch and confirm everything is fine.  It will be merged to master soon.

**Comment by craigconstantine** [comment]
At a quick glance, it looks identically-behaved. Looks fine based on my 10 seconds of testing. :)

**Comment by merefield** [comment]
Thanks!  Quite a lot of changes under the hood.  You should see FAR fewer warnings in the browser console.  I'll probably merge in a few days to master.

**Comment by merefield** [comment]
I've merged this.  Please confirm I can close this issue @craigconstantine

**Comment by craigconstantine** [comment]
I've switched back to the main branch and my original callout is fixed.

I note that suddenly a lot of the "show as tiles" topic lists— which I hadn't disabled because they _weren't_ tiled — now they are tiled. But if the configuration works; I can configure what I wish. (You clearly fixed a lot of bugs! :)

anyway. Looks fine to me.

**Comment by merefield** [comment]
Thanks, please raise additional issues for anything you find
