### ISSUE TITLE
Undesired wrapping of user avatars when preview text has no whitespace

### ISSUE THREAD

**Issue by craigconstantine** [merefield/discourse-topic-list-previews-theme#8]
It's jarring when it does it and it took me a minute to realize the thing that changed, is I just happen to have a topic with a big

`blahblbhaldksjsldkjfslkfblahblbhaldksjsldkjfslkfblahblbhaldksjsldkjfslkfblahblbhaldksjsldkjfslkfblahblbhaldksjsldkjfslkfblahblbhaldksjsldkjfslkf`

…string. Seems the CSS "priority" [dunno, I'm guessing here] is to begin wrapping the user Avatars, before breaking the no-whitespace line…

<img width="1236" alt="Screen Shot 2021-12-16 at 13 15 29" src="https://user-images.githubusercontent.com/2278992/146426714-bf9633bb-031c-43b2-abc9-43649f7a64a9.png">

<img width="1234" alt="Screen Shot 2021-12-16 at 13 15 36" src="https://user-images.githubusercontent.com/2278992/146426715-f40a8595-4329-4d85-bf8e-958fee1fb503.png">

**Comment by merefield** [comment]
You might argue the fault here is with the excerpt containing that awful link.  Yeah, ideally those awful links should be completely suppressed.   Are you in a position to install the Theme Sidecar plugin? See: https://thepavilion.io/t/which-one-to-install-plugin-or-tc/3996

**Comment by craigconstantine** [comment]
It's a hosted Discourse. I can't install plugins.

Is the excerpt generated by core Discourse? I can just post in Support over on Meta . . .

**Comment by merefield** [comment]
"Is the excerpt generated by core Discourse? I can just post in Support over on Meta . . ."

Yes it is, I'm not sure on their official line on links in excerpts but they don't seem to serve any purpose except looking really ugly and messing with styling.

Perhaps you wouldn't mind checking if it still looks ugly with the official excerpt Theme Component in isolation?  Or if you just Pin it?

**Comment by craigconstantine** [comment]
> with the official excerpt Theme Component in isolation?

I don't understand what you mean?

**Comment by merefield** [comment]
> I don't understand what you mean?

https://meta.discourse.org/t/topic-list-excerpts-theme-component/151520

**Comment by merefield** [comment]
This is the full solution presently for TLP.  Unfortunately it requires the ability to install the sidecar plugin:

https://meta.discourse.org/t/topic-list-previews-theme-component/209973/23?u=merefield

**Comment by craigconstantine** [comment]
okay, I think this is really the excerpt code's fault, not the fault of topic-list-previews. :)
