### ISSUE TITLE
Thumbnail file size too large when CDN is enabled

### ISSUE THREAD

**Issue by izzy808** [merefield/discourse-topic-list-previews-theme#9]
We are a thumbnail-heavy site. With CDN enabled, TLP is causing significant resource usage on client-side browsers to the point that browsers can become unresponsive because too many large-size images are being displayed in thumbnails as both Tiles and Lists.

Would be best if TLP regenerated thumbnails locally for thumbnails?

**Comment by FerrariFlunker** [comment]
This is quite a crucial issue- would very much appreciate to see this fixed asap.

**Comment by merefield** [comment]
We are only using thumbnails provided by Discourse.  You can use the settings in the Theme as is to reduce the resolution

**Comment by izzy808** [comment]
Just want to clarify: I did not realize downloading of external images was based on `editing grace period`

Our grace period was set high, so it was taking a long time for images to be locally generated, and before the grace period was reached the full size external images were being shown as thumbnails.

Coincidentally we had enabled CDN not long before noticing images weren't being generated locally, so I presumed it was related...

**Comment by merefield** [comment]
Ah!  Yes, that's confusing isn't it?  It's part of core Discourse behaviour we have no control over in Theme Component.  Appreciate the clarification and glad you've found the workaround @izzy808 !
